# Seed data for LASUSTECH campus.
#
# Building `code` values intentionally match the routing-node slugs defined in
# api/routing.py (e.g. "library-complex"). The AI assistant returns those slugs
# as `building_id`, and QR codes / deep links use them too, so the codes must
# line up for /buildings/<code>/ to resolve.

BUILDINGS = [
    {
        "name": "Knowledge Resource Library",
        "code": "library-complex",
        "category": "library",
        "latitude": 6.4661,
        "longitude": 3.5979,
        "description": "The campus library complex with quiet reading floors, digital archives, group study rooms, and a research support desk.",
        "image_url": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=60",
        "tags": ["study", "research", "archive", "wifi", "quiet"],
        "departments": ["Research Services", "Archives"],
        "facilities": ["Reading Rooms", "E-library", "Research Desk", "Group Study Rooms"],
        "opening_hours": "Daily 8:00 AM - 8:00 PM",
    },
    {
        "name": "ICT Innovation Centre",
        "code": "ict-center",
        "category": "facility",
        "latitude": 6.4672,
        "longitude": 3.5951,
        "description": "Hub for tech, entrepreneurship and digital skills with labs, a maker space and the campus innovation clinic.",
        "image_url": "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&q=60",
        "tags": ["tech", "innovation", "lab", "wifi"],
        "departments": ["Computer Science", "Entrepreneurship"],
        "facilities": ["Computer Labs", "Maker Space", "Innovation Clinic", "Seminar Hall"],
        "opening_hours": "Mon - Fri 8:00 AM - 6:00 PM",
    },
    {
        "name": "Engineering Block",
        "code": "engineering-block",
        "category": "faculty",
        "latitude": 6.4684,
        "longitude": 3.5968,
        "description": "Home of the engineering faculties with lecture theatres, workshops and departmental offices.",
        "image_url": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=60",
        "tags": ["engineering", "lectures", "workshop"],
        "departments": ["Mechanical Engineering", "Electrical Engineering", "Civil Engineering"],
        "facilities": ["Lecture Theatres", "Workshops", "Staff Offices", "Lab Spaces"],
        "opening_hours": "Mon - Fri 8:00 AM - 5:00 PM",
    },
    {
        "name": "Administration Tower",
        "code": "admin-tower",
        "category": "admin",
        "latitude": 6.4655,
        "longitude": 3.5946,
        "description": "Central administration: registry, bursary, admissions and the vice-chancellor's office.",
        "image_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=60",
        "tags": ["admin", "registry", "bursary"],
        "departments": ["Registry", "Bursary", "Admissions"],
        "facilities": ["Registry Counter", "Bursary Office", "Admissions Desk", "Senate Chamber"],
        "opening_hours": "Mon - Fri 9:00 AM - 4:00 PM",
    },
    {
        "name": "Science Laboratories",
        "code": "science-labs",
        "category": "lab",
        "latitude": 6.4676,
        "longitude": 3.5988,
        "description": "Teaching and research laboratories for the pure and applied sciences.",
        "image_url": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=60",
        "tags": ["science", "lab", "research"],
        "departments": ["Physics", "Chemistry", "Biology", "Mathematics"],
        "facilities": ["Chemistry Labs", "Physics Labs", "Biology Labs", "Instrumentation Room"],
        "opening_hours": "Mon - Fri 8:00 AM - 5:00 PM",
    },
    {
        "name": "Student Hub",
        "code": "student-hub",
        "category": "facility",
        "latitude": 6.4648,
        "longitude": 3.5961,
        "description": "Student union, cafeteria, relaxation lounges and the help desk for campus life.",
        "image_url": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=60",
        "tags": ["students", "cafeteria", "lounge", "wifi"],
        "departments": ["Student Affairs"],
        "facilities": ["Cafeteria", "Lounges", "Help Desk", "Event Space"],
        "opening_hours": "Daily 8:00 AM - 9:00 PM",
    },
]

EVENTS = [
    {
        "title": "Campus Innovation Summit",
        "description": "Student founders, prototypes, and lightning talks from top campus builders.",
        "date_label": "Friday",
        "start_time": "10:00 AM",
        "location_name": "ICT Innovation Centre",
        "building_code": "ict-center",
        "image_url": "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=60",
        "category": "career",
    },
    {
        "title": "Library Study Jam",
        "description": "Group study session and exam-prep clinic in the library reading rooms.",
        "date_label": "Saturday",
        "start_time": "2:00 PM",
        "location_name": "Knowledge Resource Library",
        "building_code": "library-complex",
        "image_url": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=60",
        "category": "academic",
    },
    {
        "title": "Engineering Exhibition",
        "description": "Final-year engineering projects on display with live demos.",
        "date_label": "Wednesday",
        "start_time": "11:00 AM",
        "location_name": "Engineering Block",
        "building_code": "engineering-block",
        "image_url": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=60",
        "category": "academic",
    },
    {
        "title": "Inter-Faculty Football",
        "description": "Friendly football fixtures between faculties on the sports field.",
        "date_label": "Thursday",
        "start_time": "4:00 PM",
        "location_name": "Student Hub",
        "building_code": "student-hub",
        "image_url": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=60",
        "category": "sports",
    },
]

LOST_ITEMS = [
    {
        "title": "HP Laptop",
        "description": "Black HP Pavilion 15 found near the library entrance.",
        "status": "found",
        "location_name": "Knowledge Resource Library",
        "building_code": "library-complex",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=60",
        "reported_at": "2026-07-09T08:00:00Z",
        "contact_hint": "Submitted at the Library Reception.",
    },
    {
        "title": "Student ID Card",
        "description": "Blue LASUSTECH ID card found outside the Student Hub cafeteria.",
        "status": "found",
        "location_name": "Student Hub",
        "building_code": "student-hub",
        "image_url": "",
        "reported_at": "2026-07-11T13:30:00Z",
        "contact_hint": "Collect from the Student Affairs desk.",
    },
    {
        "title": "Scientific Calculator",
        "description": "Casio fx-991 lost in the chemistry lab during practicals.",
        "status": "lost",
        "location_name": "Science Laboratories",
        "building_code": "science-labs",
        "image_url": "",
        "reported_at": "2026-07-12T15:00:00Z",
        "contact_hint": "Contact the lab attendant if found.",
    },
]

# Course -> building mappings so the AI assistant can resolve course prompts
# (e.g. "I have CSC 302") to a concrete building.
COURSES = [
    {"course_code": "CSC 302", "course_name": "Data Structures & Algorithms", "building_code": "ict-center"},
    {"course_code": "CSC 201", "course_name": "Computer Programming I", "building_code": "ict-center"},
    {"course_code": "ENG 101", "course_name": "Engineering Drawing", "building_code": "engineering-block"},
    {"course_code": "MEE 204", "course_name": "Thermodynamics", "building_code": "engineering-block"},
    {"course_code": "CHM 101", "course_name": "General Chemistry", "building_code": "science-labs"},
    {"course_code": "PHY 201", "course_name": "Electromagnetism", "building_code": "science-labs"},
    {"course_code": "BIO 102", "course_name": "Cell Biology", "building_code": "science-labs"},
    {"course_code": "MAT 301", "course_name": "Advanced Calculus", "building_code": "science-labs"},
]
